# Generated by Django 5.2 on 2025-04-27 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tailor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_location', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('expertise_details', models.CharField(blank=True, max_length=20, null=True)),
                ('expertise', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('category', models.CharField(blank=True, choices=[('punjabi', 'Punjabi'), ('shirt', 'Shirt'), ('pant', 'Pant'), ('women_dress', "Women's Dress")], default='None', max_length=20, null=True)),
                ('subcategory', models.CharField(blank=True, choices=[('short_punjabi', 'Short Punjabi'), ('long_punjabi', 'Long Punjabi'), ('designer_punjabi', 'Designer Punjabi'), ('formal_shirt', 'Formal Shirt'), ('casual_shirt', 'Casual Shirt'), ('half_sleeve_shirt', 'Half Sleeve Shirt'), ('formal_pant', 'Formal Pant'), ('jeans', 'Jeans'), ('cargo_pant', 'Cargo Pant'), ('salwar_kameez', 'Salwar Kameez'), ('lehenga', 'Lehenga'), ('blouse', 'Blouse'), ('saree_fall_pleat', 'Saree Fall & Pleat')], default='None', max_length=50, null=True)),
                ('services_offered', models.TextField(blank=True, default='None', null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('NID', models.CharField(max_length=20, unique=True)),
                ('purchased_products', models.JSONField(default=list)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='tailor_profiles/')),
                ('average_rating', models.FloatField(default=0.0)),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tailor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TailorCoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tailor_covers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_images', to='tailor.tailor')),
            ],
        ),
    ]
