# Generated by Django 5.2 on 2025-05-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large')], default='S', max_length=4),
        ),
    ]
